# Generated by Django 4.2.3 on 2023-07-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_bit_cost', models.FloatField(default=0)),
                ('sell_bit_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BYN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_byn_cost', models.FloatField(default=0)),
                ('sell_byn_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ethereum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_eth_cost', models.FloatField(default=0)),
                ('sell_eth_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_eur_cost', models.FloatField(default=0)),
                ('sell_eur_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RUB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rub_cost', models.FloatField(default=0)),
                ('sell_rub_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='USD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_usd_cost', models.FloatField(default=0)),
                ('sell_usd_cost', models.FloatField(default=0)),
            ],
        ),
    ]
