# Generated by Django 4.2.3 on 2023-07-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit_cost', models.FloatField(default=0)),
                ('eth_cost', models.FloatField(default=0)),
                ('usd_cost', models.FloatField(default=0)),
                ('rub_cost', models.FloatField(default=0)),
                ('byn_cost', models.FloatField(default=0)),
                ('eur_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BIT',
        ),
        migrations.DeleteModel(
            name='BYN',
        ),
        migrations.DeleteModel(
            name='Ethereum',
        ),
        migrations.DeleteModel(
            name='EUR',
        ),
        migrations.DeleteModel(
            name='RUB',
        ),
        migrations.DeleteModel(
            name='USD',
        ),
    ]
