# Generated by Django 4.2.3 on 2023-07-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='-', max_length=20)),
                ('sex', models.CharField(default='-', max_length=10)),
            ],
        ),
    ]
